## Final CNL Patterns

In this notebook, we take our manually created pattern classes with counts in order to construct a final CNL.

In [ ]:
import csv
import pandas as pd

In [ ]:
ROOT_PATH = '/content/drive/MyDrive/Masters/Thesis/contracts/rq3_actual'

INPUT_FILE = '4_input_pattern_classes.csv'

OUTPUT_FILE = '4_output_cnl_results.csv'

In [ ]:
def read_pd_no_header(file_path):
    names = ['operation', 'pattern', 'count', 'pattern_class', 'X']
    data = pd.read_csv(file_path, header=None, names=names)
    return data

In [ ]:
# Read in the data
file_path = f'{ROOT_PATH}/{INPUT_FILE}'
df = read_pd_no_header(file_path)

In [ ]:
df.head()

                operation             pattern  count        pattern_class    X
0  Happens -> conditional         after EVENT      3  CONDITIONAL_A EVENT  NaN
1  Happens -> conditional            at EVENT      1  CONDITIONAL_A EVENT    *
2  Happens -> conditional            if EVENT     25  CONDITIONAL_A EVENT  NaN
3  Happens -> conditional       in case EVENT      6  CONDITIONAL_A EVENT  NaN
4  Happens -> conditional  in the event EVENT     22  CONDITIONAL_A EVENT  NaN

In [ ]:
# Create a new column that lists the operation from original sym to updated sym
df['mapping'] = df['pattern_class'] + ': ' + df['operation']

# Reduce the dataframe to the pattern and operation
df = df[['mapping', 'count', 'operation']]

# Get list of mappings
mappings = list(df['mapping'].unique())

In [ ]:
mappings

['CONDITIONAL_A EVENT: Happens -> conditional',
 'CONDITIONAL_T EVENT: Happens -> conditional',
 'CONDITIONAL_A EVENT: termination power -> conditional',
 'CONDITIONAL_A EVENT: termination power (auto) -> conditional',
 'for TIMESPAN P_AFTER_I EVENT: Happens -> HappensWithin',
 'P_DURING TIME_PERIOD: Happens -> HappensWithin',
 'BETWEEN TIMEPOINT and TIMEPOINT: Happens -> HappensWithin',
 'within TIME_PERIOD: Happens -> HappensWithin',
 'after EVENT: Happens -> WHappensBeforeEvent',
 'P_BEFORE_E EVENT: Happens -> WHappensBeforeEvent',
 'until EVENT: Happens -> WHappensBeforeEvent',
 'following TIMESPAN from EVENT: Happens -> HappensAfter',
 'after DATE: Happens -> HappensAfter',
 '[at least] TIMESPAN P_AFTER_PF EVENT: Happens -> WHappensBefore',
 '[at least] TIMESPAN P_BEFORE_PF EVENT: Happens -> WHappensBefore',
 'within TIMESPAN P_AFTER_W EVENT: Happens -> WHappensBefore',
 'for TIMESPAN P_AFTER_I EVENT: Happens -> HappensWithin (surviving)',
 'CONDITIONAL_A EVENT: termination power -> notice to terminate',
 'until EVENT: power to suspend -> power to resume',
 'P_BEFORE_S DATE: Happens -> SHappensBefore',
 'until DATE: Happens -> SHappensBefore',
 'P_EXCEPT EVENT: Happens -> suspend obligation']

In [ ]:
results = []
for mapping in mappings:
    grouping = df[df['mapping'] == mapping]
    count = grouping['count'].sum()

    next_res = (mapping, count)
    results.append(next_res)

In [ ]:
# Output results to a file
result_path = f'{ROOT_PATH}/{OUTPUT_FILE}'

with open(result_path, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(results)